# Inference config with only a single model
_target_: kernelfoundry.algorithm.inference_server.LLMEnsemble
servers:
  - _target_: kernelfoundry.algorithm.inference_server.InferenceServer
    server_type: "openai"
    model_name: "gpt-5.2"  # see top of kernel_bench/inference_server.py for all options
    max_tokens: 5000
    temperature: 0.0
    num_completions: 1  # number of completions to generate
    verbose: False
weights: uniform