task_name: matmul # name for the kernel generation task
job_name: matmul_lnl # a name for the specific job you want to run, e.g. optimizing for Lunar Lake

gpu_arch: lnl # Short name of the target architecture
language: SYCL # The target language

# further run parameters (e.g. number of iterations, branches, etc for the evolutionary algorithm), see configs/run.yaml